/*******************************************************************************
 * Cell Name: cell4
 * Creator  : Siri Adiraju
 *
 * Revision History:
 * 10 May 2019	Generated by L-Edit
 *******************************************************************************/
#include <cstdlib>
#include <cmath>
#include <cstring>
#include <cstdio>
#include <string>
#include <time.h>

#define EXCLUDE_LEDIT_LEGACY_UPI
#include <ldata.h>

/* Begin -- Uncomment this block if you are using L-Comp. */
#include <lcomp.h>
/* End */

/* TODO: Put local functions here. */
void cell4_main(void)
{
	int iTmpUpiReturnCode = LUpi_GetReturnCode();
	/* Begin DO NOT EDIT SECTION generated by L-Edit */
	LCell        cellCurrent  = (LCell)LMacro_GetNewTCell();
	double       length       = LCell_GetParameterAsDouble(cellCurrent, "length");
	double       width        = LCell_GetParameterAsDouble(cellCurrent, "width");
	int          nombre_de_WG = LCell_GetParameterAsInt(cellCurrent, "nombre de WG");
	bool         Fillet       = LCell_GetParameterAsBoolean(cellCurrent, "Fillet");
	/* End DO NOT EDIT SECTION generated by L-Edit */

	if(LUpi_GetReturnCode())
	{
		LDialog_MsgBox("Error: Tcell failed to read parameters.");
		return;
	}
	LUpi_SetReturnCode(iTmpUpiReturnCode);


	/*Begin -- Uncomment this block if you are using L-Comp. */
		LC_InitializeStateFromCell(cellCurrent);
	/* End */

	/* TODO: Put local variables here. */

	/* TODO: Begin custom generator code.*/
	char WGLayer[] = "WG";
	char WGGROW003Layer[] = "WGGROW003";
	char WGOVL010Layer[] = "WGOVL010";
	char WGOVLHOLELayer[] = "WGOVLHOLE";
	
	LCoord L = 0;
	LCoord W = 0;
	L = LC_Microns(length);
	W = LC_Microns(width);
	/* TODO: Begin custom generator code.*/
	
	//Créer le premier waveguide en suivant les dimentions données
	LPoint ptWGLL, ptWGUR;
	ptWGLL.x = 0;
	ptWGLL.y = 0;
	ptWGUR.x = L;
	ptWGUR.y = W;
	LC_CreateBox(WGLayer, ptWGLL, ptWGUR);
	
	//Créer les autres WG en dessous
	for (int i=0; i<nombre_de_WG-1; i++){
		ptWGLL.y = ptWGLL.y-LC_Microns(1.5)-W;
		ptWGUR.y = ptWGUR.y-LC_Microns(1.5)-W;
		LC_CreateBox(WGLayer, ptWGLL, ptWGUR);
	}
	
	//Créer le WGOVLHOLE à 1.5 microns des waveguides
	LPoint ptWGOVLHOLELL, ptWGOVLHOLEUR;
	ptWGOVLHOLEUR.x = L + LC_Microns(1.5);
	ptWGOVLHOLEUR.y = W + LC_Microns(1.5);
	ptWGOVLHOLELL.x = 0 - LC_Microns(1.5);
	ptWGOVLHOLELL.y = ptWGLL.y-LC_Microns(1.5);
	LC_CreateBox(WGOVLHOLELayer, ptWGOVLHOLELL, ptWGOVLHOLEUR);
	
	//Créer le WGGROW003 à 3 microns des waveguides
	LPoint ptWGGROW003LL, ptWGGROW003UR;
	ptWGGROW003UR.x = L + LC_Microns(3);
	ptWGGROW003UR.y = W+LC_Microns(3);
	ptWGGROW003LL.x = 0 - LC_Microns(3);
	ptWGGROW003LL.y = ptWGLL.y-LC_Microns(3);
	LC_CreateBox(WGGROW003Layer, ptWGGROW003LL, ptWGGROW003UR);
	
	//Créer le WGOVL010 à 10 microns des waveguides
	LPoint ptWGOVL010LL, ptWGOVL010UR;
	ptWGOVL010UR.x = L+LC_Microns(10);
	ptWGOVL010UR.y = W+LC_Microns(10);
	ptWGOVL010LL.x = 0-LC_Microns(10);
	ptWGOVL010LL.y = ptWGLL.y-LC_Microns(10);
	LC_CreateBox(WGOVL010Layer, ptWGOVL010LL, ptWGOVL010UR);
	
	/* End custom generator code.*/
}
extern "C" int UPI_Entry_Point(void)
{
	cell4_main();
	return 1;
}
